Document: openstack-dashboard-cloudbase-theme
Title: Debian openstack-dashboard-cloudbase-theme Manual
Author: <insert document author here>
Abstract: This manual describes what openstack-dashboard-cloudbase-theme is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openstack-dashboard-cloudbase-theme/openstack-dashboard-cloudbase-theme.sgml.gz

Format: postscript
Files: /usr/share/doc/openstack-dashboard-cloudbase-theme/openstack-dashboard-cloudbase-theme.ps.gz

Format: text
Files: /usr/share/doc/openstack-dashboard-cloudbase-theme/openstack-dashboard-cloudbase-theme.text.gz

Format: HTML
Index: /usr/share/doc/openstack-dashboard-cloudbase-theme/html/index.html
Files: /usr/share/doc/openstack-dashboard-cloudbase-theme/html/*.html
